### ISSUE TITLE
Can't add any objects

### ISSUE THREAD

**Issue by sphaero** [d3cod3/Mosaic#10]
I was pointed to this project on ARS Electronica. I know this project is still in alpha but is there any way I can try some stuff already. I've compiled Mosaic on Debian and it is running. I can open examples (like videocrop) but I can't add any objects. Any pointers would be appreciated!

**Comment by d3cod3** [comment]
Hi sphaero,

have you tried the objects menu? if you click on one object from the list nothing happens?

Or you can right click on the patch, and a floating menu will appear, there you have all the available objects ordered by category (the same as the objects in the main menu)

Please, let me know what is happening, if needed post some screenshot too!

**Comment by sphaero** [comment]
I can open context menus or from the objects menu but nothing happens 
Here's a short screencast

![recorded](https://user-images.githubusercontent.com/832465/64605424-60a53000-d3c4-11e9-9c9d-b679755a7321.gif)

**Comment by d3cod3** [comment]
That's weird! Where did you download and launched the debian install script?

I'm thinking that could be a writing permission issue, just try to open Mosaic as sudo and see if objects appear. That's because Mosaic auto-save and modify patch files on the fly, so to add objects you need writing permission of the editing patch (a new one or a previously saved one).

If this is the issue, then you'll need to re-install Mosaic launching the script in a user-space folder, to avoid the sudo permissions.

**Comment by sphaero** [comment]
Yes indeed this resolves it. It was already a bit eccentric that the install script installed everything as root and system wide (opt). Perhaps it would be easier to just install in a subdir of where the script is invoked? It doesn't require root anyway, not?

I'm playing around with it now. Are you interested in crash reports?

I guess you can close this issue?

**Comment by sphaero** [comment]
btw I just did a `chown -R <user> /opt/openFrameworks` which also makes it run as a user

**Comment by d3cod3** [comment]
Ok, it must be something about the system, because the install script just do a chown -R <user> over the install folder at the end.

Anyway, thanks for the feedback, sure let me know about bugs and stuff you find, i'm working to release the beta on December, so any help will be appreciated!

Bye
