### ISSUE TITLE
Nodes (objects) port from ofxDatGui --> ImGui

### ISSUE THREAD

**Issue by d3cod3** [d3cod3/Mosaic#18]

**Comment by d3cod3** [comment]
![mosaicScreenshot_200414](https://user-images.githubusercontent.com/141075/79212958-ae958100-7e48-11ea-8d80-aa3aa3ef7f81.jpg)

I'm having trouble drawing OF stuff inside objects, it seems like imgui is always  rendering on top of everything.

In the image you can see the video grabber object rendering the webcam image under the object window.

Did you know how to solve this?

**Comment by Daandelange** [comment]
Hmm, I didn't think about that case where you need to draw the GUI from OF.
One way would be to let objects draw after ImGui has flushed the graphics pipeline, so you can draw on top of it. (This happens when you call `ofxImGui->end()` in auto mode or `ofxImGui->draw()` in manual mode with my fork.)  
Otherwise, we might be able to make a transparent zone so we can draw behind objects.
Both feel pretty hacky...

Another option is to [link a texture-ID](https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples#example-for-opengl-users) in order to display images. An image tex id can be an FBO tex ID, I think.  
Do lots of objects have/need "custom GUIs" ? (involving drawing from OF)

**Comment by d3cod3** [comment]
Basically most of the objects that works with video/webcam/images, drawing ofTextures inside the objects, and sound objects with signal waveform visualizer (ofPolyline) or fft data (audio analysis).

The linking of a texture id from an FBO seems the better choice, i'll check it.

Don't like the transparent zone option, but i'm going to try them all and we'll talk again.

**Comment by d3cod3** [comment]
Got it!

using ofTexture with proper allocate:

```c
ofTextureData texData;
texData.width = camWidth;
texData.height = camHeight;
texData.textureTarget = GL_TEXTURE_2D;
texData.bFlipTexture = true;
static_cast<ofTexture *>(_outletParams[0])->allocate(texData);
```

and calling a method from ofxImGui helpers did the trick:

`ofxImGui::AddImage(*static_cast<ofTexture *>(_outletParams[0]), ImVec2(this->width*_nodeCanvas.GetCanvasScale(), this->height*_nodeCanvas.GetCanvasScale()));`

So, problem solved, for ofPolyline waveform graphics, with ofTexture.bind()/unbind() will work!

![mosaicScreenshot_200415](https://user-images.githubusercontent.com/141075/79327140-3b594100-7f14-11ea-8eff-69b0edfa0f6d.jpg)

**Comment by Daandelange** [comment]
Yes, the FBO option would be the best option, that keeps Gui separated and "canalised" (with API methods). (don't spend too much time on the other solutions?)
[Seems pretty simple to do in fact](https://gamedev.stackexchange.com/questions/140693/how-can-i-render-an-opengl-scene-into-an-imgui-window).
One drawback with FBOs : on small hardware (with integrated GPU), we'll have to check what the FBO limit is and what happens when there's too much FBO objects to allocate ? We can always disable preview mode on nodes if hardware doesn't allow having too much.

For plotting, checkout the ImGui demo `ImGui::PlotHistogram()`, eventually [some ImGuiExtension](https://github.com/soulthreads/imgui-plot). Although drawing the GUI with OF will give a better example on how to use object data ?

Edit: Ok, great, works fine for FBOs. :)

**Comment by d3cod3** [comment]
Actually there's no need for FBO, just using the link ofTexture pointer, so no GPU limits problem, it works like a charm!

But is a really good idea to have a mechanism enabling/disabling automatic preview depending on the resources

Great the plotting from imgui, i'll check it!

**Comment by d3cod3** [comment]
![Sin título](https://user-images.githubusercontent.com/141075/84405325-4543ab80-ac08-11ea-94d2-58f9b94ea9eb.jpeg)

![photo_2020-06-11 17 23 50](https://user-images.githubusercontent.com/141075/84405427-62787a00-ac08-11ea-8e29-004bee388743.jpeg)

![photo_2020-06-11 17 24 07](https://user-images.githubusercontent.com/141075/84405443-686e5b00-ac08-11ea-8f94-42e2ba4bb66f.jpeg)

Porting objects...

**Comment by d3cod3** [comment]
![Sin título](https://user-images.githubusercontent.com/141075/85220895-8e85bf00-b3af-11ea-9081-3c6062dd4b68.jpeg)

![Sin título2](https://user-images.githubusercontent.com/141075/85220897-92194600-b3af-11ea-9f97-cf3a633edb37.jpeg)

oscillator and envelopes sound objects

this starts to look good!

**Comment by d3cod3** [comment]
![Sin título](https://user-images.githubusercontent.com/141075/85306001-28339600-b4ae-11ea-8980-8cb9c6a6d655.jpeg)
