### ISSUE TITLE
unable to load saved patch 

### ISSUE THREAD

**Issue by spezi** [d3cod3/Mosaic#40]
Got error while open saved patch on linux ubuntu Studio 20.04 :

[pdsp] engine: closing...
[pdsp] engine: audio streams closed and resources released
Instance is already registered with name = time
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 3) >= this->size() (which is 3)
Aborted (core dumped)

Best Regards
spezi

**Comment by d3cod3** [comment]
Hi, can you please give me some more info about the problem

have you installed Mosaic with the [Mosaic Installer](https://github.com/d3cod3/Mosaic-Installer) or with the currently alpha version on flatpak?

The patch you were trying to open, can you post the file ( the .xml ), so i can check it.

Have you tried to re-open Mosaic and re-load the patch? same error?

**Comment by spezi** [comment]
Hi, thanks for the fast response. I used the Mosaic Installer and re-open Mosaic and patch too. It seams there is a audio problem with jack and pulse on Ubuntu Studio. I will try to install Mosaic on another Manjaro Linux Instance. Here the zipped .xml, because .xml upload isn't allowed here.  
[beat_osc.zip](https://github.com/d3cod3/Mosaic/files/5697117/beat_osc.zip)

**Comment by d3cod3** [comment]
Hey @spezi, thanks for the patch, it seems like there was no issues with audio, actually your case helped me find and solve a bug in the osc sender object, the out of range came from  there:

https://github.com/d3cod3/ofxVisualProgramming/commit/68bc8a42602374ee4fe8325b39a08493bc4550e2

So, thanks for the indirect help, and your patch now re-open without issues

![mosaicScreenshot_201218](https://user-images.githubusercontent.com/141075/102628167-939ead80-4149-11eb-85dc-07dbb5250056.jpg)

In order to have the last fix in your Mosaic, you just need to re-launch the Mosaic installer script, this time will be faster because will just update stuff and re-compile Mosaic.

Let me know if everything is working!

**Comment by spezi** [comment]
hi d3cod3,

i'm glad to assist you .. Patch is now loading without issues.
For a while, i started to build a Projection Mapping Software with openframeworks, but i started to learn C++ too ;) Mosaic is excectly, what i waited for. thanks a lot for your work !! 

Best Regards
spezi

**Comment by d3cod3** [comment]
I'm glad it's working!

closing this issue as solved.
