### ISSUE TITLE
Mosaic patch in xCode

### ISSUE THREAD

**Issue by dimdieo** [d3cod3/Mosaic#58]
Is it possible to create a patch in Mosaic and then build on it project in xCode with Openframeworks for ios app?

**Comment by Daandelange** [comment]
Mosaic can compile via xCode for osx (a few years ago at least), but I don't think it will work on iOS. Technically, there's probably multiple incompatible ofxAddon libraries and the shaders might need to be ported to GL ES. This said, Mosaic is based on OpenFrameworks which supports iOS so porting it should not be that difficult.  
@d3cod3 , you probably know the iOs situation better than me, can you confirm / complete my answer ?

**Comment by d3cod3** [comment]
Sorry, but no, i never tested Mosaic code on iOS, so no idea!

That said, to have a patch transfered to an xCode project or a qtcreator one should not be trivial but probaby possible, it's something for sure worth researching.

Right now the ofxAddons list has been reduced, and probably it should not be difficult to make the code compile for iOS removing some objects, the one using thise addons for sure:

ofxFFmpegRecorder
ofxHapPlayer
ofxNDI

Then there is the big question about ofxPDSP ( i know that ofxPd can compile on iOS), because the entire audio part of Mosaic is builded over ofxPDSP, and if that do not compile then it's game over.

No more info on the subject for now, let's think about it!

**Comment by dimdieo** [comment]
Thanks a lot for the answers!  It would be great to make prototypes in Mosaic and then finish the project in xCode working only on the interface for iOS app.  Unfortunately, in Max and PD (with the ofxPD plugin) this is not very convenient.  I am currently working on my first app in Openframeworks using ofxPDSP and accidentally found your project. The idea of ​​a graphical interface for ofxPDSP is great and I hope it will be continued!

**Comment by d3cod3** [comment]
Yes, right now in Mosaic we have those implemented from ofxPDSP:

![Captura de pantalla 2023-01-07 a las 15 35 09](https://user-images.githubusercontent.com/141075/211156003-bd705948-cdc6-46fa-90f0-5d08c23f1b00.png)

and more stuff for audio analysis
