### ISSUE TITLE
inputs in glsl nodes

### ISSUE THREAD

**Issue by lkytk** [d3cod3/Mosaic#61]
hello, 

first, thank you for this amazing tool!
I might be missing something but I can't seem to use the inputs of the glsl nodes, whether it is a number or a texture.
It feels like the value is set back to default when the input is connected.

thanks

**Comment by d3cod3** [comment]
Hi, maybe it's an issue with input numbers?

Numbers need a bang ( or a trigger for continous send ) in order to send data

![Captura de pantalla 2023-01-26 a las 13 51 23](https://user-images.githubusercontent.com/141075/214840232-579e0856-1814-4d26-a503-ce385c7a812b.png)

And are you using the last release? (0.6.5)

Which OS?

Anyway, thanks for trying out Mosaic!

**Comment by lkytk** [comment]
okay thanks, I wasn't aware that I needed a bang to send the data, so now it works with numbers.
As for the video, I was using 0.6.3, so it seems that it had been corrected in the last version.
(I have another problem with hap files now, but for the time being I will manage with mp4 & prores)

thank you!
