### ISSUE TITLE
"there has been a problem compiling Debug OF library"

### ISSUE THREAD

**Issue by hellocatfood** [d3cod3/Mosaic#74]
I'm trying to install Mosaic using the automated installer on Ubuntu 23.04. After it installs all system packages I get an error about it not being able to compile the debug OF library. Below is the full error

[debug.txt](https://github.com/d3cod3/Mosaic/files/12608987/debug.txt)

**Comment by d3cod3** [comment]
Hi, the problem is related with an openframeworks library file, if you know about this stuff, you can modify the file following this patch:

https://github.com/flathub/org.d3cod3.Mosaic/blob/master/openframeworks-libsndfile.patch

and this one:

https://github.com/flathub/org.d3cod3.Mosaic/blob/master/openal_fix.patch

then run again the automated installer

In case you want the easy way, you can install Mosaic with flatpak:

https://flathub.org/apps/org.d3cod3.Mosaic
