### ISSUE TITLE
Control config parameters?

### ISSUE THREAD

**Issue by sphaero** [d3cod3/Mosaic#78]
Probably a noob question but is it possible to control some config params though objects/nodes?

For example can I connect a gui/slider object to control the alpha of one of the texture mixer channels?

**Comment by Daandelange** [comment]
Hi there @sphaero :)

`Object < Math < Number` should be what you are looking for ? (connected to `texture.alpha`)
![image](https://github.com/d3cod3/Mosaic/assets/1329784/b4c1a75c-83eb-4c8e-84fc-4c9578853b1e)

**Comment by d3cod3** [comment]
Hi, generally it's like @Daandelange is telling you, but not specifically for the ```texture mixer``` object, because it's not designed to have external control of the channel alphas 
![Screenshot from 2023-11-23 10-19-57](https://github.com/d3cod3/Mosaic/assets/141075/e2d1d352-e6cc-46d1-b79f-bb60028d040c)

As you can see, we just have the texture inlets ( blue ones ).

I'll add a vector inlet in the future to externally control the channels alphas!

**Comment by sphaero** [comment]
Ok thanks for the feedback. Mosaic is looking good btw!

**Comment by d3cod3** [comment]
Updated ```texture mixer``` object, this [980b76312c87b59dfb0828a63a260966b16c512c](https://github.com/d3cod3/ofxVisualProgramming/commit/980b76312c87b59dfb0828a63a260966b16c512c) adds a vector inlet to externally control textures alpha

![Screenshot from 2024-11-04 22-10-30](https://github.com/user-attachments/assets/e5527002-3fa4-4718-ab73-4fc5a9d37300)
